
export const FETCH_LIST_EMPLOYEE='FETCH_LIST_EMPLOYEE';
export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const REMOVE_EMPLOYEE = 'REMOVE_EMPLOYEE';
export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE';
export const EMPLOYEE_FAIL='EMPLOYEE_FAIL';
export const FETCH_EMPLOYEE_START='FETCH_EMPLOYEE_START';
export const ADD_EMPLOYEE_START='ADD_EMPLOYEE_START';
export const UPDATE_EMPLOYEE_START='UPDATE_EMPLOYEE_START';
export const REMOVE_EMPLOYEE_START='REMOVE_EMPLOYEE_START';
export const DEF='DEF';
//Faculty
export const FETCH_FACULTY_SUCCESS = 'FETCH_FACULTY_SUCCESS';
export const FETCH_FACULTY_START = 'FETCH_FACULTY_START';

//Comment
export const FETCH_COMMENT_SUCCESS = 'FETCH_COMMENT_SUCCESS';
export const FETCH_COMMENT_START = 'FETCH_COMMENT_START';

//Topic
export const FETCH_TOPIC_SUCCESS = 'FETCH_TOPIC_SUCCESS';
export const FETCH_TOPIC_START = 'FETCH_TOPIC_START';
export const SET_TOPIC='SET_TOPIC'

//Permission
export const FETCH_PERMISSION_SUCCESS = 'FETCH_PERMISSION_SUCCESS';
export const FETCH_PERMISSION_START = 'FETCH_PERMISSION_START';

//Science
export const FETCH_SCIENCE_SUCCESS = 'FETCH_SCIENCE_SUCCESS';
export const FETCH_SCIENCE_START = 'FETCH_SCIENCE_START';

//Subject
export const FETCH_SUBJECT_SUCCESS = 'FETCH_SUBJECT_SUCCESS';
export const FETCH_SUBJECT_START = 'FETCH_SUBJECT_START';

//User
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_START = 'LOGIN_USER_START';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_START = 'LOGOUT_USER_START';