export const DEF='DEF';
//Faculty
export const FETCH_FACULTY_SUCCESS = 'FETCH_FACULTY_SUCCESS';
export const FETCH_FACULTY_START = 'FETCH_FACULTY_START';

//Comment
export const FETCH_COMMENT_SUCCESS = 'FETCH_COMMENT_SUCCESS';
export const FETCH_COMMENT_START = 'FETCH_COMMENT_START';

//Topic
export const FETCH_TOPIC_SUCCESS = 'FETCH_TOPIC_SUCCESS';
export const FETCH_TOPIC_START = 'FETCH_TOPIC_START';
export const SET_TOPIC='SET_TOPIC'

//Permission
export const FETCH_PERMISSION_SUCCESS = 'FETCH_PERMISSION_SUCCESS';
export const FETCH_PERMISSION_START = 'FETCH_PERMISSION_START';

//Science
export const FETCH_SCIENCE_SUCCESS = 'FETCH_SCIENCE_SUCCESS';
export const FETCH_SCIENCE_START = 'FETCH_SCIENCE_START';

//Subject
export const FETCH_SUBJECT_SUCCESS = 'FETCH_SUBJECT_SUCCESS';
export const FETCH_SUBJECT_START = 'FETCH_SUBJECT_START';

//User
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_START = 'LOGIN_USER_START';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_START = 'LOGOUT_USER_START';

//List
export const SET_SCIENCE_ID = 'SET_SCIENCE_ID';
export const SET_FACULTY_ID='SET_FACULTY_ID';